### ISSUE TITLE
Dot net 5.0

### ISSUE THREAD

**Issue by mariante** [UnidentifiedX/YTSearch.NET#2]
Hello!
 Thanks for sharing this amazing package.
 Is there a possible to make it compatible with dot net 5.0 too? The 2 current versions are for dot net 6.0.

Thanks

**Comment by UnidentifiedX** [comment]
hello!

I've added support for dotnet 5.0 to the project and I'll publish it soon after I iron out a few bugs

should be out in a day or two

edit: added support in commit 75969ac26b892acc1ecca8d2bd5a1460684261e7

**Comment by mariante** [comment]
I'll keep waiting for nuget package with last version.
Thanks again. You awesome!
