### ISSUE TITLE
Error System.FormatException in .NET 8

### ISSUE THREAD

**Issue by slagusev** [UnidentifiedX/YTSearch.NET#5]
When using the GetVideoMetadataAsync method, the error is: System.FormatException: "String '2021-12-03T10:04:03-08:00' was not recognized as a valid DateTime."

**Comment by UnidentifiedX** [comment]
@slagusev could you send the link to the youtube video? I'll have a look at it

**Comment by slagusev** [comment]
@UnidentifiedX https://www.youtube.com/watch?v=7ghsl2HNEo4

**Comment by slagusev** [comment]
@UnidentifiedX I downloaded the repository in the class YouTubeSearchClient, and I fixed lines 151 and 152 to "yyyy-MM-ddTHH:mm:sszzz". It worked.

**Comment by UnidentifiedX** [comment]
@slagusev Looks like YouTube updated its way of storing dates so it's different from how it was when I first published this package. Thanks for pointing this out! Addressed in commit c3de460789398d3384f499296fa140ca6268a98a
