### ISSUE TITLE
viewCount, int.Parse error large or small

### ISSUE THREAD

**Issue by slagusev** [UnidentifiedX/YTSearch.NET#9]
Hello! At some points, retrieving the view count caused an error

![изображение_2024-08-29_194242055](https://github.com/user-attachments/assets/dd8254d2-8e42-4b4e-b981-0ad83d356a92)

At the moment, I changed it to long, and so far there haven't been any errors, but I might have done something wrong and should have left it as int.

`var views = long.Parse((string?)videoDetail?["viewCount"]);`

line 144 on YouTubeSearchClient

The search was conducted using "https://github.com/UnidentifiedX/YTSearch.NET/issues/6" from the topic "beautiful girls"

**Comment by B0N3head** [comment]
Yeah, would have to change that as videos with super big view counts like baby shark go over the 32bit int limit. 
I've created a pull request with credit to you for finding the issue 🤙

https://github.com/UnidentifiedX/YTSearch.NET/pull/10
